version: "3"

services:
  app:
    build: ./
    restart: always
    container_name: kirara-bot
    links:
      - redis
      - database
    depends_on:
      - database
      - redis
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: kirara
      POSTGRES_USER: kirara
  redis:
    image: redis
