version: "3"

services:
  midori:
    build: ./context/midori
    container_name: midori
    links:
      - redis
      - database
    depends_on:
      - redis
      - database
    environment:
      HOST: 0.0.0.0
      NODE_ENV: development
      PG_PASSWORD: kirara
    ports:
      - "7865:5171"
    env_file:
      - .env.dev
  app:
    build: ./
    restart: always
    container_name: kirara-bot
    links:
      - redis
      - database
      - midori
    depends_on:
      - database
      - redis
      - midori
    environment:
      PG_PASSWORD: kirara
      NODE_ENV: development
    env_file:
      - .env.dev
  database:
    image: postgres
    ports:
      - "7866:5432"
    environment:
      POSTGRES_PASSWORD: kirara
      POSTGRES_USER: kirara
  redis:
    image: redis
