name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - "*.md"
      - "LICENSE"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "*.md"
      - "LICENSE"

jobs:
  ci:
    name: Node 18 on ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint
