name: CI

on:
  push:
    branches:
      - master
      - dev
    paths-ignore:
      - "*.md"
      - "LICENSE"
  pull_request:
    branches:
      - dev
      - master
    paths-ignore:
      - "*.md"
      - "LICENSE"

jobs:
  ci:
    name: Node 18 on ubuntu-latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
          registry-url: "https://registry.npmjs.org/"

      - name: Install system dependencies
        run: |
          DEBIAN_FRONTEND="noninteractive" sudo apt-get install -yqq --no-install-recommends --no-install-suggests \
          build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint
