name: Deploy to Kirara Beta

on:
  push:
    branches: [dev]

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST_BETA }}
          username: kirara
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd
            cd Kirara
            git fetch
            git add .
            git reset --hard origin/dev
            npm i --omit=dev
            pm2 restart kirara
